// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectToDB(arg1) {
  return window['go']['core']['App']['ConnectToDB'](arg1);
}

export function DefaultFetchTableData(arg1, arg2, arg3) {
  return window['go']['core']['App']['DefaultFetchTableData'](arg1, arg2, arg3);
}

export function ExportColumnDataType() {
  return window['go']['core']['App']['ExportColumnDataType']();
}

export function FetchSchema(arg1) {
  return window['go']['core']['App']['FetchSchema'](arg1);
}

export function ListTables() {
  return window['go']['core']['App']['ListTables']();
}

export function TestConnection(arg1) {
  return window['go']['core']['App']['TestConnection'](arg1);
}
