// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';

export function ConnectToDB(arg1:core.DBConfig):Promise<string>;

export function ListTables():Promise<core.Tables>;
