// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectToDB(arg1) {
  return window['go']['core']['App']['ConnectToDB'](arg1);
}

export function ListTables() {
  return window['go']['core']['App']['ListTables']();
}
